# Generated by Django 2.2.1 on 2019-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='boards',
            new_name='Board',
        ),
    ]
